# Generated by Django 4.2.3 on 2023-07-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
