# Generated by Django 4.2.3 on 2023-07-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_alter_callback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='message',
            field=models.TextField(default='.ללא הודעה', max_length=100, null=True),
        ),
    ]
