# Generated by Django 4.2.3 on 2023-07-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0003_alter_callback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='message',
            field=models.TextField(default='.ללא הודעה', max_length=350, null=True),
        ),
    ]
